module.exports = {
    PORT: process.env.PORT || 3000,
    mongodb: process.env.mongodb || 'mongodb://localhost:27017/user',
    ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET || 'secretToken',
    REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET || 'refereshSecretToken',
    NOT_FOUND_ERR: 'user not found',
    FIELDS_ARE_EMPTY_ERR: 'some fields are empty',
    FILE_IS_UPDATE: 'files is update',
    EMAIL_IS_ALREADY_USE: 'this email is already in use',
    DELETE_STATUS_SUCCESS: 'success delete',
    UNKNOWN_ERROR: 'Unknown error',
    DATABASE_IS_EMPTY: 'database is empty',
    AUTHORIZATION: 'AUTHORIZATION',
    LIFE_CYCLE_ACCESS_TOKEN: '10m',
    LIFE_CYCLE_REFRESH_TOKEN: '31d',
    ACCESS: 'accessToken',
    REFRESH: 'refreshToken',
    BODY: 'body',
    EMAIL_FIELD: 'email',
};
